name: Example

on:
  push:
    branches:
      - test/action

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: leedonggyu/terradrift@v1.0.1
        with:   
          name: "leedonggyu" 